### ISSUE TITLE
Am I correct in observing that map can only map to the same type?

### ISSUE THREAD

**Issue by asegs** [mariomac/gostream#3]
For example []int -> []int, but not []string -> []int.  I'm running into the same problem due to the method type parameter rules, so I can't use method chaining on my own Stream API.  Curious to understand your abstract system and method/function equality better.

**Comment by mariomac** [comment]
Hi @asegs , yes you are right, but only if you use Map as a method of a stream. This [limitation comes from Go](https://github.com/golang/go/issues/49085). 

To map to a different type, there is also `Map` as a function. Please check Example 3 in the README: https://github.com/mariomac/gostream#example-3-generation-from-an-iterator-map-to-a-different-type

**Comment by asegs** [comment]
Yep, this is exactly the same conclusion I came to working on my own version of this.  Well, that's frustrating but I'm happy that the shortcoming wasn't mine.  Thank you very much for the response and confirmation.
