### ISSUE TITLE
handling nested stream

### ISSUE THREAD

**Issue by jtejido** [mariomac/gostream#5]
I'm trying to port a java code that has something nested like this:

```
return minutiae.stream()
.sorted(Comparator.<FeatureMinutia>comparingInt(
	minutia -> minutiae.stream()
		.mapToInt(neighbor -> minutia.position.minus(neighbor.position).lengthSq())
		.sorted()
		.skip(Parameters.SORT_BY_NEIGHBOR)
		.findFirst().orElse(Integer.MAX_VALUE))
	.reversed())
.limit(Parameters.MAX_MINUTIAE)
.collect(toList());
```

**minutiae** is a slice. How can we handle nested streaming using this library,

**Comment by mariomac** [comment]
Hi @jtejido ,

I think nothing should prevent you from doing `stream.OfSlice(minutiae)` to instantiate the first stream, and then do again `stream.OfSlice(minutiae)` inside an inner function.

Cheers!
